version: '2'
services:
  spingularchatsql6-app:
    image: spingularchatsql6
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://spingularchatsql6-postgresql:5432/spingularchatsql6
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  spingularchatsql6-postgresql:
    extends:
      file: postgresql.yml
      service: spingularchatsql6-postgresql
